=== Julian155/Todo-REST-API-Client/src/Transfer/Templates/schema.xsd
<xs:schema attributeFormDefault="unqualified" targetNamespace="transfer-schema" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="transfers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="transfer" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="name" use="optional"/>
                                            <xs:attribute type="xs:string" name="type" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Julian155/Todo-REST-API-Client/src/Shared/Payment/Transfer/payment_transfer.xml
<?xml version="1.0" encoding="utf-8"?>
<transfers xmlns="transfer-schema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="transfer-schema ../../../Transfer/Templates/schema.xsd">

    <transfer name="Payment">
        <property name="arrivedAt" type="string"/>
        <property name="departuredAt" type="string"/>
        <property name="licencePlate" type="string"/>
        <property name="amount" type="float"/>
    </transfer>

    <transfer name="Ticket">
        <property name="licencePlate" type="string"/>
        <property name="arrivedAt" type="string"/>
        <property name="longTermParkerId" type="int"/>
    </transfer>

</transfers>

=== Julian155/Todo-REST-API-Client/src/Shared/ParkingStatus/Transfer/parking_status_transfer.xml
<?xml version="1.0" encoding="utf-8"?>
<transfers xmlns="transfer-schema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="transfer-schema ../../../Transfer/Templates/schema.xsd">

    <transfer name="Status">
        <property name="id" type="int"/>
        <property name="einfahrtzeit" type="string"/>
        <property name="ausfahrtzeit" type="string"/>
        <property name="parkplatzId" type="int"/>
        <property name="parkerId" type="int"/>
    </transfer>

    <transfer name="Parkplatz">
        <property name="id" type="int"/>
        <property name="reserviert" type="bool"/>
    </transfer>

    <transfer name="ParkingSpace">
        <property name="freeNormalParkingSpaces" type="int"/>
        <property name="freeReservedParkingSpaces" type="int"/>
    </transfer>
</transfers>

=== Julian155/Todo-REST-API-Client/src/Shared/Parker/Transfer/parker_transfer.xml
<?xml version="1.0" encoding="utf-8"?>
<transfers xmlns="transfer-schema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="transfer-schema ../../../Transfer/Templates/schema.xsd">

    <transfer name="DauerParker">
        <property name="vorname" type="string"/>
        <property name="nachname" type="string"/>
    </transfer>

    <transfer name="Parker">
        <property name="id" type="int"/>
        <property name="kennzeichen" type="string"/>
        <property name="dauerparkerId" type="int"/>
    </transfer>
</transfers>
